CREATE TABLE "GCG_3533_ATT_SUM"(
 "BIRUNID" BIGINT, 
 "EMPLOYEE_ID" VARCHAR(5),
 "EMPLOYEE_NAME" VARCHAR(30),
 "DEPARTMENT" VARCHAR(4),
 "HOURS_PROD" DOUBLE,
 "HOURS_NON_PROD" DOUBLE,
 "HOURS_REG" DOUBLE,
 "HOURS_OT" DOUBLE,
 "HOURS_TA" DOUBLE,
 "HOURS_JOBS" DOUBLE,
 "DOLLARS_PAY" DOUBLE,
 "DOLLARS_NON_PROD" DOUBLE,
 "DOLLARS_PROD" DOUBLE);